AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 900
    MemorySize: 3008

Resources:
  GenerateFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 767828769405.dkr.ecr.us-east-2.amazonaws.com/jam-api:docker
      ImageConfig:
        Command: ["jam.lambda_handler"]
      Events:
        GenerateAPI:
          Type: Api
          Properties:
            Path: /api/generate
            Method: post
            RestApiId: !Ref ApiGatewayApi
      Environment:
        Variables:
          PYTORCH_ENABLE_MPS_FALLBACK: "1"
    Metadata:
      DockerTag: python3.9-v1
      DockerContext: .
      Dockerfile: Dockerfile

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'POST, OPTIONS'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'*'"

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/generate"
  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt GenerateFunction.Arn
